### ISSUE TITLE
  File "striker.py", line 175, in dnsdump TypeError: list indices must be integers, not str

### ISSUE THREAD

**Issue by hktalent** [TheYahya/sherlock#85]
![image](https://user-images.githubusercontent.com/18223385/50696315-1243d280-107a-11e9-9bb4-3341a0ace3ac.png)
```
Traceback (most recent call last):
  File "striker.py", line 243, in <module>
    dnsdump(domain)
  File "striker.py", line 175, in dnsdump
    for entry in res['dns_records']['dns']:
TypeError: list indices must be integers, not str
```

**Comment by hktalent** [comment]
sorry
