### ISSUE TITLE
ModuleNotFoundError: No module named 'idna'

### ISSUE THREAD

**Issue by Dentrax** [TheYahya/sherlock#86]
I installed required packages:

`pip3 install -r requirements.txt --user`

```
Requirement already satisfied: requests in /home/dentrax/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.21.0)
Requirement already satisfied: requests_futures in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (0.9.9)
Requirement already satisfied: torrequest in /home/dentrax/.local/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (0.1.0)
Requirement already satisfied: colorama in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (0.4.1)
Requirement already satisfied: idna in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/lib/python3.7/site-packages (from requests->-r requirements.txt (line 1)) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/dentrax/.local/lib/python3.7/site-packages (from requests->-r requirements.txt (line 1)) (2018.11.29)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.7/site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: stem>=1.4.0 in /usr/lib/python3.7/site-packages (from torrequest->-r requirements.txt (line 3)) (1.7.1)
Requirement already satisfied: PySocks>=1.5.7 in /usr/lib/python3.7/site-packages (from torrequest->-r requirements.txt (line 3)) (1.6.8)
```

And also:

`pip3 install idna --user`

`Requirement already satisfied: idna in /usr/lib/python3.7/site-packages (2.8)`

Testing:

`python3 sherlock.py test`

Error:

```
Traceback (most recent call last):
  File "sherlock.py", line 18, in <module>
    import requests
  File "/home/dentrax/.local/lib/python3.7/site-packages/requests/__init__.py", line 113, in <module>
    from . import packages
  File "/home/dentrax/.local/lib/python3.7/site-packages/requests/packages.py", line 7, in <module>
    locals()[package] = __import__(package)
ModuleNotFoundError: No module named 'idna'
```

**Comment by Dentrax** [comment]
I have just fixed that with: `pip install -I --user idna` :)
